name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@cmake_args
        with:
          apt-dependencies: 'pkg-config'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  bionic-ci-plus:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@cmake_args
        with:
          apt-dependencies: 'pkg-config'
          cmake-args: '-DBUILDSYSTEM_TESTING=True'
